### ISSUE TITLE
Hit counter not working

### ISSUE THREAD

**Issue by ApurvShah007** [deep5050/deep5050#1]
HEy, I just wanted to point out that the hit counter is not working because that API you are using has reached the query limit. Here is a suggestion: 

 ![visitors](https://visitor-badge.laobi.icu/badge?page_id=deep5050.deep5050)

**Comment by deep5050** [comment]
Hi @ApurvShah007 , thanks for the badge. I'm tired of changing hit counter APIs. hope this one will work for long :)

**Comment by ApurvShah007** [comment]
So this one is hosted on a public server so it should not be an issue. It has not crashed for me in around 3 weeks so its going to be fine.
